#################### Colors ####################
HeaderTextColor="#4c4f69"
DateTextColor="#4c4f69"
TimeTextColor="#4c4f69"

FormBackgroundColor="#e6e9ef"
BackgroundColor="#eff1f5"
DimBackgroundColor="#eff1f5"

LoginFieldBackgroundColor="#ccd0da"
PasswordFieldBackgroundColor="#ccd0da"
LoginFieldTextColor="#4c4f69"
PasswordFieldTextColor="#4c4f69"
UserIconColor="#8839ef"
PasswordIconColor="#8839ef"

PlaceholderTextColor="#6c6f85"
WarningColor="#d20f39"

LoginButtonTextColor="#eff1f5"
LoginButtonBackgroundColor="#40a02b"
SystemButtonsIconsColor="#40a02b"
SessionButtonTextColor="#40a02b"
VirtualKeyboardButtonTextColor="#40a02b"

DropdownTextColor="#4c4f69"
DropdownSelectedBackgroundColor="#acb0be"
DropdownBackgroundColor="#ccd0da"

HighlightTextColor="#eff1f5"
HighlightBackgroundColor="#8839ef"
HighlightBorderColor="#1e66f5"

HoverUserIconColor="#8839ef"
HoverPasswordIconColor="#8839ef"
HoverSystemButtonsIconsColor="#40a02b"
HoverSessionButtonTextColor="#40a02b"
HoverVirtualKeyboardButtonTextColor="#40a02b"
