[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""
Font="JetBrainsMono"
FontSize="13"
KeyboardSize="0.4"
RoundCorners="20"
Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText=""

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/default"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################
HeaderTextColor="#e0def4"
DateTextColor="#e0def4"
TimeTextColor="#e0def4"

FormBackgroundColor="#2a273f"
BackgroundColor="#232136"
DimBackgroundColor="#232136"

LoginFieldBackgroundColor="#393552"
PasswordFieldBackgroundColor="#393552"
LoginFieldTextColor="#e0def4"
PasswordFieldTextColor="#e0def4"
UserIconColor="#c4a7e7"
PasswordIconColor="#c4a7e7"

PlaceholderTextColor="#908e9c"
WarningColor="#eb6f92"

LoginButtonTextColor="#232136"
LoginButtonBackgroundColor="#3e8fb0"
SystemButtonsIconsColor="#3e8fb0"
SessionButtonTextColor="#3e8fb0"
VirtualKeyboardButtonTextColor="#3e8fb0"

DropdownTextColor="#e0def4"
DropdownSelectedBackgroundColor="#44415a"
DropdownBackgroundColor="#393552"

HighlightTextColor="#232136"
HighlightBackgroundColor="#c4a7e7"
HighlightBorderColor="#9ccfd8"

HoverUserIconColor="#c4a7e7"
HoverPasswordIconColor="#c4a7e7"
HoverSystemButtonsIconsColor="#3e8fb0"
HoverSessionButtonTextColor="#3e8fb0"
HoverVirtualKeyboardButtonTextColor="#3e8fb0"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="32"
Blur=""

HaveFormBackground="false"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
