[General]
ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""
Font="JetBrainsMono"
FontSize="13"
KeyboardSize="0.4"
RoundCorners="20"
Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText=""

BackgroundPlaceholder=""
Background="Backgrounds/default"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#575279"
DateTextColor="#797593"
TimeTextColor="#575279"

FormBackgroundColor="#fffaf3"
BackgroundColor="#faf4ed"
DimBackgroundColor="#faf4ed"

LoginFieldBackgroundColor="#f2e9e1"
PasswordFieldBackgroundColor="#f2e9e1"
LoginFieldTextColor="#575279"
PasswordFieldTextColor="#575279"
UserIconColor="#907aa9"
PasswordIconColor="#907aa9"

PlaceholderTextColor="#9893a5"
WarningColor="#b4637a"

LoginButtonTextColor="#faf4ed"
LoginButtonBackgroundColor="#286983"
SystemButtonsIconsColor="#286983"
SessionButtonTextColor="#286983"
VirtualKeyboardButtonTextColor="#286983"

DropdownTextColor="#575279"
DropdownSelectedBackgroundColor="#dfdad9"
DropdownBackgroundColor="#f2e9e1"

HighlightTextColor="#faf4ed"
HighlightBackgroundColor="#907aa9"
HighlightBorderColor="#56949f"

HoverUserIconColor="#907aa9"
HoverPasswordIconColor="#907aa9"
HoverSystemButtonsIconsColor="#286983"
HoverSessionButtonTextColor="#286983"
HoverVirtualKeyboardButtonTextColor="#286983"

PartialBlur="true"
FullBlur=""
BlurMax="32"
Blur=""

HaveFormBackground="false"
FormPosition="center"

VirtualKeyboardPosition="center"

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
