name: Build Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install vsce
        run: npm install -g @vscode/vsce
        
      - name: Build Extension
        run: vsce package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tokyo-Night-Dark-Enhanced
          path: D:\a\Tokyo-Night-Dark-Enhanced\Tokyo-Night-Dark-Enhanced\tokyo-night-dark-enhanced-1.10.0.vsix 
