; COLOR EXPLANATION
; main, sidebar, player = background
; card                  = cards, tracklist, dropdowns, input fields
; shadow                = text on button, tab active & selected row
; selected row          = selected song & tab
; button-active         = play button, outline on focused input
; button                = all other buttons
; button-disabled       = volume & seekbar background, scrollbar handle, borders, hover

[blue-dark]
text               = bde6fb
subtext            = 6d8692
main               = 1e2529
sidebar            = 1e2529
player             = 1e2529
card               = 171d20
shadow             = 171d20
selected-row       = bde6fb
button             = bde6fb
button-active      = bde6fb
button-disabled    = 2a3439
tab-active         = bde6fb
notification       = 171d20
notification-error = fb7c7c
misc               = 1e2529

[tokyonight-moon]
text               = C8D3F5    
subtext            = A9B1D6     
main               = 232437    
sidebar            = 232437
player             = 232437
card               = 232437    
shadow             = 232437
selected-row       = C8D3F5     
button             = 7AA2F7    
button-active      = 7AA2F7
button-disabled    = 3B4261     
tab-active         = 7AA2F7
notification       = 16161E     
notification-error = F7768E    
misc               = 1A1B26

[dracula]
text               = F8F8F2
subtext            = BD93F9
main               = 282a36
sidebar            = 282a36
player             = 282a36
card               = 282a36
shadow             = 282a36
selected-row       = BD93F9
button             = FF79C6
button-active      = FF79C6
button-disabled    = 6272A4
tab-active         = BD93F9
notification       = 44475A
notification-error = FF5555
misc               = 6272A4

[kanagawa]
text               = DCD7BA
subtext            = A6A69C
nav-active-text    = DCD7BA
main               = 23232B
sidebar            = 1F1F28
player             = 23232B
card               = 2A2A37
shadow             = 16161D
main-secondary     = 363646
button             = 7E9CD8
button-secondary   = 957FB8
button-active      = 7E9CD8
button-disabled    = 727169
nav-active         = 363646
play-button        = 7E9CD8
tab-active         = 363646
notification       = 363646
notification-error = C34043
misc               = 727169

[catppuccin-latte]
text               = 4c4f69
subtext            = 6c6f85
nav-active-text    = 4c4f69
main               = eff1f5
sidebar            = e6e9ef
player             = eff1f5
card               = ccd0da
shadow             = bcc0cc
main-secondary     = ccd0da
button             = 8839ef
button-secondary   = ea76cb
button-active      = 8839ef
button-disabled    = acb0be
nav-active         = ccd0da
play-button        = 1e66f5
tab-active         = ccd0da
notification       = ccd0da
notification-error = d20f39
misc               = 7c7f93

[rosepine-dawn]
text               = 575279
subtext            = 797593
nav-active-text    = 575279
main               = faf4ed
sidebar            = faf4ed
player             = faf4ed
card               = f2e9e1
shadow             = dfdad9
main-secondary     = f2e9e1
button             = 907aa9
button-secondary   = d7827e
button-active      = 907aa9
button-disabled    = cecacd
nav-active         = dfdad9
play-button        = 907aa9
tab-active         = dfdad9
notification       = f2e9e1
notification-error = b4637a
misc               = 9893a5

[rosepine-moon]
text               = e0def4
subtext            = 908e9c
nav-active-text    = e0def4
main               = 282639
sidebar            = 282639
player             = 282639
card               = 2a273f
shadow             = 1f1d2e
main-secondary     = 2a273f
button             = c4a7e7
button-secondary   = ea9a97
button-active      = c4a7e7
button-disabled    = 56526e
nav-active         = 393552
play-button        = c4a7e7
tab-active         = 393552
notification       = 2a273f
notification-error = eb6f92
misc               = 6e6a86

[nord]
text               = D8DEE9         # nord4 — основной текст
subtext            = 81A1C1         # nord9 — акцентный текст
main               = 2e3240         # nord0 — фон
sidebar            = 2e3240         # nord0 — фон боковой панели
player             = 2e3240         # nord0 — фон плеера
card               = 2e3240         # nord0 — фон карточек
shadow             = 2e3240         # nord0 — тень
selected-row       = 81A1C1         # nord9 — выделенная строка
button             = 88C0D0         # nord10 — кнопка
button-active      = 88C0D0         # nord10 — активная кнопка
button-disabled    = 4C566A         # nord3 — отключённая кнопка
tab-active         = 81A1C1         # nord9 — активная вкладка
notification       = 3B4252         # nord2 — уведомление
notification-error = BF616A         # nord11 — ошибка
misc               = 4C566A         # nord3 — прочее


[gruvbox-material-dark-hard]
text               = D4BE98
subtext            = BDAE93
main               = 282828
sidebar            = 282828
player             = 282828
card               = 282828
shadow             = 282828
selected-row       = D4BE98
button             = 8ec07c
button-active      = 8ec07c
button-disabled    = 665C54
tab-active         = 8ec07c
notification       = 282828
notification-error = FB4934
misc               = 3C3836

[gruvbox-material-light-soft]
text               = 3C3836
subtext            = 665C54
main               = F2E5BC
sidebar            = F2E5BC
player             = F2E5BC
card               = F2E5BC
shadow             = F2E5BC
selected-row       = 665C54
button             = 8F9A52
button-active      = 427B58
button-disabled    = BDAE93
tab-active         = 427B58
notification       = 665C54
notification-error = C14720
misc               = F2E5BC

[catppuccin-macchiato]
text               = CAD3F5
subtext            = A6ADC8
main               =24273A
sidebar            =24273A
player             =24273A
card               =24273A
shadow             =24273A
selected-row       = CAD3F5
button             = 7FB4CA
button-active      = 7FB4CA
button-disabled    = 5B6078
tab-active         = 7FB4CA
notification       =1E2030
notification-error = ED8796
misc               =1E2030


[blue-light]
text               = 123354
subtext            = 8495a7
main               = f5f7fa
sidebar            = f5f7fa
player             = f5f7fa
card               = ffffff
shadow             = ffffff
selected-row       = 22c5fd
button             = 22c5fd
button-active      = 22c5fd
button-disabled    = c8d0d9
tab-active         = 22c5fd
notification       = ffffff
notification-error = fb7c7c
misc               = f5f7fa

[gray-dark]
text               = ffffff
subtext            = 909090
main               = 202020
sidebar            = 202020
player             = 202020
card               = 191919
shadow             = 191919
selected-row       = ffffff
button             = ffffff
button-active      = ffffff
button-disabled    = 313131
tab-active         = ffffff
notification       = 191919
notification-error = fb7c7c
misc               = 202020

[gray-light]
text               = 29292a
subtext            = 909091
main               = f7f7f7
sidebar            = f7f7f7
player             = f7f7f7
card               = ffffff
shadow             = ffffff
selected-row       = 61717c
button             = 61717c
button-active      = 61717c
button-disabled    = cecece
tab-active         = 61717c
notification       = ffffff
notification-error = fb7c7c
misc               = f7f7f7

[green-dark]
text               = bbf1dd
subtext            = 6b8a7f
main               = 1b2421
sidebar            = 1b2421
player             = 1b2421
card               = 151c19
shadow             = 151c19
selected-row       = bbf1dd
button             = bbf1dd
button-active      = bbf1dd
button-disabled    = 27332f
tab-active         = bbf1dd
notification       = 151c19
notification-error = fb7c7c
misc               = 1b2421

[green-light]
text               = 19483e
subtext            = 88a19c
main               = f6f9f9
sidebar            = f6f9f9
player             = f6f9f9
card               = e5eceb
shadow             = ffffff
selected-row       = 2ae18e
button             = 2ae18e
button-active      = 2ae18e
button-disabled    = cad6d4
tab-active         = 2ae18e
notification       = e5eceb
notification-error = fb7c7c
misc               = f6f9f9

[orange-dark]
text               = fcc8b4
subtext            = 927367
main               = 271e1b
sidebar            = 271e1b
player             = 271e1b
card               = 1e1715
shadow             = 1e1715
selected-row       = fcc8b4
button             = fcc8b4
button-active      = fcc8b4
button-disabled    = 372b26
tab-active         = fcc8b4
notification       = 1e1715
notification-error = fb7c7c
misc               = 271e1b

[orange-light]
text               = 563b25
subtext            = a89a8e
main               = faf8f7
sidebar            = faf8f7
player             = faf8f7
card               = ffffff
shadow             = ffffff
selected-row       = ff8265
button             = ff8265
button-active      = ff8265
button-disabled    = d9d2cd
tab-active         = ff8265
notification       = ffffff
notification-error = fb7c7c
misc               = faf8f7

[purple-dark]
text               = d8c4f1
subtext            = 7d718c
main               = 221f26
sidebar            = 221f26
player             = 221f26
card               = 1a181e
shadow             = 1a181e
selected-row       = d8c4f1
button             = d8c4f1
button-active      = d8c4f1
button-disabled    = 302b36
tab-active         = d8c4f1
notification       = 1a181e
notification-error = fb7c7c
misc               = 221f26

[purple-light]
text               = 402b4d
subtext            = 9d91a3
main               = f9f7f9
sidebar            = f9f7f9
player             = f9f7f9
card               = ffffff
shadow             = ffffff
selected-row       = 9f74e7
button             = 9f74e7
button-active      = 9f74e7
button-disabled    = d4ced7
tab-active         = 9f74e7
notification       = ffffff
notification-error = fb7c7c
misc               = f9f7f9

[red-dark]
text               = fdb4b4
subtext            = 6d8692
main               = 271b1b
sidebar            = 271b1b
player             = 271b1b
card               = 1e1515
shadow             = 1e1515
selected-row       = fdb4b4
button             = fdb4b4
button-active      = fdb4b4
button-disabled    = 372626
tab-active         = fdb4b4
notification       = 1e1515
notification-error = fb7c7c
misc               = 271b1b

[red-light]
text               = 572920
subtext            = a9908b
main               = faf7f6
sidebar            = faf7f6
player             = faf7f6
card               = ffffff
shadow             = ffffff
selected-row       = ff5966
button             = ff5966
button-active      = ff5966
button-disabled    = d9cecb
tab-active         = ff5966
notification       = ffffff
notification-error = fb7c7c
misc               = faf7f6

[rose-pine]
text               = e0def4
subtext            = 908caa
main               = 191724
sidebar            = 191724
player             = 191724
card               = 26233a
shadow             = 26233a
selected-row       = ebbcba
button             = ebbcba
button-active      = ebbcba
button-disabled    = 1f1d2e
tab-active         = ebbcba
notification       = 26233a
notification-error = eb6f92
misc               = 191724

[rose-pine-moon]
text               = e0def4
subtext            = 908caa
main               = 232136
sidebar            = 232136
player             = 232136
card               = 393552
shadow             = 393552
selected-row       = ebbcba
button             = ebbcba
button-active      = ebbcba
button-disabled    = 2a273f
tab-active         = ebbcba
notification       = 393552
notification-error = eb6f92
misc               = 232136

[rose-pine-dawn]
text               = 575279
subtext            = 797593
main               = f2e9e1
sidebar            = f2e9e1
player             = f2e9e1
card               = faf4ed
shadow             = faf4ed
selected-row       = d7827e
button             = d7827e
button-active      = d7827e
button-disabled    = faf4ed
tab-active         = d7827e
notification       = faf4ed
notification-error = b4637a
misc               = f2e9e1

[tokyo-night]
text               = B5B9D6
subtext            = 747F8D
main               = 242638
sidebar            = 242638
player             = 242638
card               = 1C1D2B
shadow             = 1C1D2B
selected-row       = B5B9D6
button             = B5B9D6
button-active      = B5B9D6
button-disabled    = 747F8D
tab-active         = B5B9D6
notification       = B5B9D6
notification-error = 747F8D
misc               = 1E2529
