# /* ---- 🌊 Kanagawa Wave 🌊 ---- */ #

source = $HOME/.config/hypr/wallust/wallust-hyprland.conf
$Scripts = $HOME/.config/hypr/scripts

general {
    grace = 1
    fractional_scaling = 2
    immediate_render = true
}

background {
    monitor =
    path = /usr/share/sddm/themes/simple_sddm_2/Backgrounds/default
    color = rgb(23232b)
    noise = 0.01
    contrast = 1.0
    brightness = 0.8
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}

# Date
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%A, %-d %B')" </b>"
    color = rgb(c34043)
    font_size = 22
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -150
    halign = center
    valign = center
}

# Hour-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = rgb(7e9cd8)
    font_size = 220
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -50
    halign = center
    valign = top
}

# Minute-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = rgb(957fb8)
    font_size = 220
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -350
    halign = center
    valign = top
}

# Seconds-Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%S")"
    color = rgb(727169)
    font_size = 50
    font_family = JetBrainsMono Nerd Font Medium
    position = 0, -360
    halign = center
    valign = top
}

# USER
label {
    monitor =
    text =   $USER
    color = rgb(7e9cd8)
    font_size = 26
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 220
    halign = center
    valign = bottom
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 65
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(7e9cd8)
    inner_color = rgb(23232b)
    capslock_color = rgb(c34043)
    font_color = rgb(dcd7ba)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font Medium
    placeholder_text = <i><span foreground="##727169">󰌾 Password...</span></i>
    hide_input = false
    position = 0, 100
    halign = center
    valign = bottom
}

# Keyboard LAYOUT
label {
    monitor =
    text = $LAYOUT
    color = rgb(54546d)
    font_size = 14
    font_family = JetBrainsMono Nerd Font Medium
    position = 0, 65
    halign = center
    valign = bottom
}

# battery information
label {
    monitor =
    text = cmd[update:1000] echo "<b> "$($Scripts/Battery.sh)" </b>"
    color = rgb(76946a)
    font_size = 18
    font_family = JetBrainsMono Nerd Font Medium
    position = 0, 30
    halign = right
    valign = bottom
}

# weather
label {
    monitor =
    text = cmd[update:3600000] [ -f "$HOME/.cache/.weather_cache" ] && cat "$HOME/.cache/.weather_cache"
    color = rgb(7e9cd8)
    font_size = 18
    font_family = JetBrainsMono Nerd Font Medium
    position = 50, 0
    halign = left
    valign = bottom
}

# Decorative line
label {
    monitor =
    text = ──────────────────────
    color = rgb(363646)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, 180
    halign = center
    valign = bottom
}

# Current year
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%Y')"
    color = rgb(54546d)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -190
    halign = center
    valign = center
}
