source = $HOME/.config/hypr/wallust/wallust-hyprland.conf
$Scripts = $HOME/.config/hypr/scripts

general {
    grace = 1
    fractional_scaling = 2
    immediate_render = true
}

background {
    monitor =
    path = /usr/share/sddm/themes/simple_sddm_2/Backgrounds/default

    noise = 0.01
    contrast = 1.1
    brightness = 0.9
    vibrancy = 0.1
    vibrancy_darkness = 0.0
}

label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%A, %-d %B')" </b>"
    color = rgb(ea9a97)
    font_size = 22
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = rgb(c4a7e7)
    font_size = 220
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -50
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = rgb(3e8fb0)
    font_size = 220
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, -350
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%S")"
    color = rgb(f6c177)
    font_size = 50
    font_family = JetBrainsMono Nerd Font Medium
    position = 0, -360
    halign = center
    valign = top
}

label {
    monitor =
    text =   $USER
    color = rgb(9ccfd8)
    font_size = 26
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 220
    halign = center
    valign = bottom
}

input-field {
    monitor =
    size = 250, 65
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(c4a7e7)
    inner_color = rgb(35,33,54)
    capslock_color = rgb(eb6f92)
    font_color = rgb(e0def4)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font Medium
    placeholder_text = <i><span foreground="##6e6a86">󰌾 Введите пароль...</span></i>
    hide_input = false
    position = 0, 100
    halign = center
    valign = bottom
}

label {
    monitor =
    text = $LAYOUT
    color = rgb(90,140,170)
    font_size = 14
    font_family = JetBrainsMono Nerd Font Medium
    position = 0, 65
    halign = center
    valign = bottom
}

label {
    monitor =
    text = cmd[update:1000] echo "<b> "$($Scripts/Battery.sh)" </b>"
    color = rgb(3e8fb0)
    font_size = 18
    font_family = JetBrainsMono Nerd Font Medium
    position = 0, 30
    halign = right
    valign = bottom
}

label {
    monitor =
    text = cmd[update:3600000] [ -f "$HOME/.cache/.weather_cache" ] && cat "$HOME/.cache/.weather_cache"
    color = rgb(9ccfd8)
    font_size = 18
    font_family = JetBrainsMono Nerd Font Medium
    position = 50, 0
    halign = left
    valign = bottom
}

label {
    monitor =
    text = ──────────────────────
    color = rgb(57,53,82)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, 180
    halign = center
    valign = bottom
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%Y')"
    color = rgb(f6c177)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -190
    halign = center
    valign = center
}
